language: python
python:
    - "2.7"

cache: apt
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran

branches:
  only:
    - develop2

# command to install dependencies
before_install:
    - pip install --upgrade pip setuptools wheel
    - pip install numpy --only-binary=numpy
    - pip install scipy --only-binary=scipy

install:
    - pip install -r requirements.txt
    - pip install flake8

before_script:
    flake8 .

# command to run tests
script: python manage.py test
